import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: ['./src/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#6b00b0',
        'on-secondary': '#680012',
        'primary-container': '#00d4ff',
        'surface-dim': '#131313',
        outline: '#859398',
        'on-secondary-container': '#5b000f',
        primary: '#a8e8ff',
        tertiary: '#efd6ff',
        'primary-fixed': '#b4ebff',
        'on-secondary-fixed-variant': '#92001e',
        'on-tertiary-container': '#7800c5',
        'primary-fixed-dim': '#3cd7ff',
        'outline-variant': '#3c494e',
        'tertiary-container': '#ddb2ff',
        'surface-container-high': '#2a2a2a',
        'surface-bright': '#3a3939',
        'inverse-on-surface': '#313030',
        'surface-container': '#201f1f',
        'on-error-container': '#ffdad6',
        'on-primary': '#003642',
        'tertiary-fixed-dim': '#dfb7ff',
        'surface-container-lowest': '#0e0e0e',
        secondary: '#ffb3b2',
        'on-primary-fixed-variant': '#004e5f',
        'inverse-surface': '#e5e2e1',
        'on-surface-variant': '#bbc9cf',
        'tertiary-fixed': '#f1daff',
        'on-tertiary': '#4b007e',
        'surface-container-highest': '#353534',
        'error-container': '#93000a',
        'on-background': '#e5e2e1',
        'secondary-container': '#ff525c',
        'surface-tint': '#3cd7ff',
        'secondary-fixed': '#ffdad8',
        'surface-container-low': '#1c1b1b',
        background: '#131313',
        'inverse-primary': '#00677e',
        'on-primary-fixed': '#001f27',
        'surface-variant': '#353534',
        'on-error': '#690005',
        'on-secondary-fixed': '#410008',
        'on-tertiary-fixed': '#2d004f',
        'on-surface': '#e5e2e1',
        'on-primary-container': '#00586b',
        error: '#ffb4ab',
        surface: '#131313',
        'secondary-fixed-dim': '#ffb3b2',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'margin-mobile': '16px',
        gutter: '24px',
        'margin-desktop': '64px',
        'container-max': '1440px',
        unit: '4px',
      },
      fontFamily: {
        'display-lg': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'headline-lg': ['var(--font-sora)', 'Sora', 'sans-serif'],
        'ui-header': ['var(--font-geist)', 'Geist', 'sans-serif'],
        'data-mono': ['var(--font-geist)', 'Geist', 'sans-serif'],
        'body-md': ['var(--font-manrope)', 'Manrope', 'sans-serif'],
        'headline-lg-mobile': ['var(--font-sora)', 'Sora', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'ui-header': ['14px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '600' }],
        'data-mono': ['12px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', fontWeight: '700' }],
      },
      maxWidth: {
        'container-max': '1440px',
      },
    },
  },
  plugins: [],
};

export default config;
